-- MySQL Script generated by MySQL Workbench
-- Sat Jan 16 02:44:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema reha
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `reha` ;

-- -----------------------------------------------------
-- Schema reha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reha` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `reha` ;

-- -----------------------------------------------------
-- Table `reha`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reha`.`person` ;

CREATE TABLE IF NOT EXISTS `reha`.`person` (
                                               `id_person` INT NOT NULL AUTO_INCREMENT,
                                               `name` VARCHAR(45) NOT NULL,
                                               `last_name` VARCHAR(45) NOT NULL,
                                               `gender` ENUM('MALE', 'FEMALE') NOT NULL,
                                               `role` ENUM('ROLE_PATIENT', 'ROLE_NURSE', 'ROLE_DOCTOR', 'ROLE_ADMIN') NOT NULL DEFAULT 'ROLE_PATIENT',
                                               `username` VARCHAR(50) NULL DEFAULT NULL,
                                               `email` VARCHAR(50) NULL DEFAULT NULL,
                                               `password` VARCHAR(100) NULL DEFAULT NULL,
                                               `enabled` TINYINT(1) NOT NULL DEFAULT '1',
                                               `id_insurance` VARCHAR(45) NULL DEFAULT NULL,
                                               PRIMARY KEY (`id_person`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 3
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reha`.`treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reha`.`treatment` ;

CREATE TABLE IF NOT EXISTS `reha`.`treatment` (
                                                  `id_treatment` INT NOT NULL AUTO_INCREMENT,
                                                  `id_doctor` INT NOT NULL,
                                                  `id_person` INT NOT NULL,
                                                  `diagnosis` VARCHAR(200) NULL DEFAULT NULL,
                                                  `started` DATE NOT NULL,
                                                  `ended` DATE NULL DEFAULT NULL,
                                                  PRIMARY KEY (`id_treatment`),
                                                  INDEX `id_doctor` (`id_doctor` ASC) VISIBLE,
                                                  INDEX `id_person` (`id_person` ASC) VISIBLE,
                                                  CONSTRAINT `treatment_ibfk_1`
                                                      FOREIGN KEY (`id_doctor`)
                                                          REFERENCES `reha`.`person` (`id_person`),
                                                  CONSTRAINT `treatment_ibfk_2`
                                                      FOREIGN KEY (`id_person`)
                                                          REFERENCES `reha`.`person` (`id_person`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reha`.`assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reha`.`assignment` ;

CREATE TABLE IF NOT EXISTS `reha`.`assignment` (
                                                   `id_assignment` INT NOT NULL AUTO_INCREMENT,
                                                   `id_treatment` INT NOT NULL,
                                                   `type` ENUM('MEDICATION', 'PROCEDURE') NOT NULL,
                                                   `name` VARCHAR(45) NOT NULL,
                                                   `pattern_quantity` INT NOT NULL,
                                                   `pattern_howlong` INT NOT NULL,
                                                   `pattern_timeframe` ENUM('HOUR', 'DAY', 'WEEK', 'MONTH') NOT NULL DEFAULT 'DAY',
                                                   `started` DATE NOT NULL,
                                                   `expired` DATE NULL DEFAULT NULL,
                                                   `comments` VARCHAR(200) NULL DEFAULT NULL,
                                                   PRIMARY KEY (`id_assignment`),
                                                   INDEX `id_treatment` (`id_treatment` ASC) VISIBLE,
                                                   CONSTRAINT `assignment_ibfk_1`
                                                       FOREIGN KEY (`id_treatment`)
                                                           REFERENCES `reha`.`treatment` (`id_treatment`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reha`.`med_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reha`.`med_event` ;

CREATE TABLE IF NOT EXISTS `reha`.`med_event` (
                                                  `id_med_event` INT NOT NULL AUTO_INCREMENT,
                                                  `id_assignment` INT NOT NULL,
                                                  `starts` DATETIME NOT NULL,
                                                  `status` ENUM('PENDING', 'SCHEDULED', 'DONE', 'CANCELED') NOT NULL,
                                                  `id_nurse` INT NOT NULL,
                                                  PRIMARY KEY (`id_med_event`),
                                                  INDEX `id_assignment` (`id_assignment` ASC) VISIBLE,
                                                  INDEX `id_nurse` (`id_nurse` ASC) VISIBLE,
                                                  CONSTRAINT `med_event_ibfk_1`
                                                      FOREIGN KEY (`id_assignment`)
                                                          REFERENCES `reha`.`assignment` (`id_assignment`),
                                                  CONSTRAINT `med_event_ibfk_2`
                                                      FOREIGN KEY (`id_nurse`)
                                                          REFERENCES `reha`.`person` (`id_person`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
