-- MySQL Script generated by MySQL Workbench
-- Mon Jan 25 07:51:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema reha
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `reha` ;

-- -----------------------------------------------------
-- Schema reha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reha` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `reha` ;

-- -----------------------------------------------------
-- Table `reha`.`pattern`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reha`.`pattern` ;

CREATE TABLE IF NOT EXISTS `reha`.`pattern` (
                                                `id_pattern` INT NOT NULL AUTO_INCREMENT,
                                                `monday` TINYINT(1) NOT NULL DEFAULT '0',
                                                `tuesday` TINYINT(1) NOT NULL DEFAULT '0',
                                                `wednesday` TINYINT(1) NOT NULL DEFAULT '0',
                                                `thursday` TINYINT(1) NOT NULL DEFAULT '0',
                                                `friday` TINYINT(1) NOT NULL DEFAULT '0',
                                                `saturday` TINYINT(1) NOT NULL DEFAULT '0',
                                                `sunday` TINYINT(1) NOT NULL DEFAULT '0',
                                                `morning` TINYINT(1) NOT NULL DEFAULT '0',
                                                `day` TINYINT(1) NOT NULL DEFAULT '0',
                                                `evening` TINYINT(1) NOT NULL DEFAULT '0',
                                                PRIMARY KEY (`id_pattern`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reha`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reha`.`user` ;

CREATE TABLE IF NOT EXISTS `reha`.`user` (
                                             `id_user` INT NOT NULL AUTO_INCREMENT,
                                             `username` VARCHAR(50) NOT NULL,
                                             `password` VARCHAR(100) NOT NULL,
                                             `role` ENUM('ROLE_PATIENT', 'ROLE_NURSE', 'ROLE_DOCTOR', 'ROLE_ADMIN') NOT NULL,
                                             `email` VARCHAR(50) NOT NULL,
                                             `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             `enabled` TINYINT(1) NOT NULL DEFAULT '1',
                                             PRIMARY KEY (`id_user`),
                                             UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 5
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reha`.`med_staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reha`.`med_staff` ;

CREATE TABLE IF NOT EXISTS `reha`.`med_staff` (
                                                  `id_med_staff` INT NOT NULL AUTO_INCREMENT,
                                                  `name` VARCHAR(50) NOT NULL,
                                                  `last_name` VARCHAR(50) NOT NULL,
                                                  `gender` ENUM('MALE', 'FEMALE') NOT NULL,
                                                  `specialty` VARCHAR(50) NOT NULL,
                                                  `id_user` INT NOT NULL,
                                                  PRIMARY KEY (`id_med_staff`),
                                                  INDEX `fk_user_id_idx` (`id_user` ASC) VISIBLE,
                                                  CONSTRAINT `fk_staff_user_id`
                                                      FOREIGN KEY (`id_user`)
                                                          REFERENCES `reha`.`user` (`id_user`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 5
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reha`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reha`.`patient` ;

CREATE TABLE IF NOT EXISTS `reha`.`patient` (
                                                `id_patient` INT NOT NULL AUTO_INCREMENT,
                                                `name` VARCHAR(50) NOT NULL,
                                                `last_name` VARCHAR(50) NOT NULL,
                                                `gender` ENUM('MALE', 'FEMALE') NOT NULL,
                                                `id_insurance` VARCHAR(50) NOT NULL,
                                                `id_user` INT NOT NULL,
                                                PRIMARY KEY (`id_patient`),
                                                UNIQUE INDEX `id_insurance_UNIQUE` (`id_insurance` ASC) VISIBLE,
                                                INDEX `fk_patient_user_id_idx` (`id_user` ASC) VISIBLE,
                                                CONSTRAINT `fk_patient_user_id`
                                                    FOREIGN KEY (`id_user`)
                                                        REFERENCES `reha`.`user` (`id_user`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 2
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reha`.`treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reha`.`treatment` ;

CREATE TABLE IF NOT EXISTS `reha`.`treatment` (
                                                  `id_treatment` INT NOT NULL AUTO_INCREMENT,
                                                  `id_doctor` INT NOT NULL,
                                                  `id_patient` INT NOT NULL,
                                                  `opened` DATE NOT NULL,
                                                  `diagnosis` VARCHAR(300) NULL DEFAULT NULL,
                                                  `opened_comments` VARCHAR(300) NOT NULL,
                                                  `closed` DATE NULL DEFAULT NULL,
                                                  `closed_comments` VARCHAR(300) NULL DEFAULT NULL,
                                                  PRIMARY KEY (`id_treatment`),
                                                  INDEX `fk_treatment_doctor_idx` (`id_doctor` ASC) VISIBLE,
                                                  INDEX `fk_treatment_patient_idx` (`id_patient` ASC) VISIBLE,
                                                  CONSTRAINT `fk_treatment_doctor`
                                                      FOREIGN KEY (`id_doctor`)
                                                          REFERENCES `reha`.`med_staff` (`id_med_staff`),
                                                  CONSTRAINT `fk_treatment_patient`
                                                      FOREIGN KEY (`id_patient`)
                                                          REFERENCES `reha`.`patient` (`id_patient`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reha`.`assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reha`.`assignment` ;

CREATE TABLE IF NOT EXISTS `reha`.`assignment` (
                                                   `id_assignment` INT NOT NULL AUTO_INCREMENT,
                                                   `id_treatment` INT NOT NULL,
                                                   `type` ENUM('MEDICATION', 'PROCEDURE') NOT NULL,
                                                   `name` VARCHAR(50) NOT NULL,
                                                   `dosage` VARCHAR(50) NOT NULL,
                                                   `quantity` INT NOT NULL,
                                                   `id_pattern` INT NOT NULL,
                                                   `assignment_opened` DATE NOT NULL,
                                                   `assignment_closed` DATE NULL DEFAULT NULL,
                                                   `closed_comments` VARCHAR(300) NULL DEFAULT NULL,
                                                   PRIMARY KEY (`id_assignment`),
                                                   INDEX `fk_assignment_treatment_idx` (`id_treatment` ASC) VISIBLE,
                                                   INDEX `fk_assignment_pattern_idx` (`id_pattern` ASC) VISIBLE,
                                                   CONSTRAINT `fk_assignment_pattern`
                                                       FOREIGN KEY (`id_pattern`)
                                                           REFERENCES `reha`.`pattern` (`id_pattern`),
                                                   CONSTRAINT `fk_assignment_treatment`
                                                       FOREIGN KEY (`id_treatment`)
                                                           REFERENCES `reha`.`treatment` (`id_treatment`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reha`.`med_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reha`.`med_event` ;

CREATE TABLE IF NOT EXISTS `reha`.`med_event` (
                                                  `id_med_event` INT NOT NULL AUTO_INCREMENT,
                                                  `id_assignment` INT NOT NULL,
                                                  `id_nurse` INT NOT NULL,
                                                  `starts` DATETIME NOT NULL,
                                                  `status` ENUM('PENDING', 'SCHEDULED', 'DONE', 'CANCELED') NOT NULL DEFAULT 'SCHEDULED',
                                                  `id_patient` INT NOT NULL,
                                                  `closed_comments` VARCHAR(100) NULL DEFAULT NULL,
                                                  PRIMARY KEY (`id_med_event`),
                                                  INDEX `id_assignment` (`id_assignment` ASC) VISIBLE,
                                                  INDEX `fk_med_event_nurse_idx` (`id_nurse` ASC) VISIBLE,
                                                  INDEX `fk_med_event_patient_idx` (`id_patient` ASC) VISIBLE,
                                                  CONSTRAINT `fk_med_event_assignment`
                                                      FOREIGN KEY (`id_assignment`)
                                                          REFERENCES `reha`.`assignment` (`id_assignment`),
                                                  CONSTRAINT `fk_med_event_nurse`
                                                      FOREIGN KEY (`id_nurse`)
                                                          REFERENCES `reha`.`med_staff` (`id_med_staff`),
                                                  CONSTRAINT `fk_med_event_patient`
                                                      FOREIGN KEY (`id_patient`)
                                                          REFERENCES `reha`.`patient` (`id_patient`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
